{{ with .Values }}
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: {{ .namespace.install }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
{{ end }}