{{ with .Values }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-group
  namespace: {{ .namespace.install }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
    - {{ .namespace.target }}
{{- end }}